#!/usr/bin/env php
<?php

require getcwd() . '/vendor/autoload.php';

use AntonioPrimera\LaraPackager\Commands\CreateGitignore;
use Symfony\Component\Console\Application;

$application = new Application();

//register commands
$application->add(new CreateGitignore());

$application->run();